name: Docker python image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Push image to docker hub
    runs-on: ubuntu-latest
    steps:
    - name: Login into Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: virt-proj
        file: /Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER_NAME }}/clockbox:latest
   
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker_python_image
